Task_1/AuctionStore/AuctionStore.UI/Controllers/AuctionHouseController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AuctionStore.Business.Abstract;
using AuctionStore.Business.Entities;
using AuctionStore.Business.Infrastructure;
using AuctionStore.UI.Models;
using AutoMapper;
using NLog;

namespace AuctionStore.UI.Controllers
{
    [HandleError(View = "ErrorView")]
    public class AuctionHouseController : Controller
    {
        private readonly Lazy<IAuctionStore> _houses;

        private readonly Lazy<ILogger> _logger;

        private IConnectionStore _connectionStore;

        public AuctionHouseController(Lazy<IAuctionStore> houses, Lazy<ILogger> logger)
        {
            _houses = houses;
            _logger = logger;
        }

        public ViewResult Create()
        {
            return View(new AuctionHouseViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(AuctionHouseViewModel house)
        {
            if (ModelState.IsValid)
            {
                _houses.Value.Create(Mapper.Map<AuctionHouseViewModel, AuctionHouse>(house));
                _connectionStore = new ConnectionStore(house.Type, _logger);
                _connectionStore.AddConnection(house.Location);

                _logger.Value.Info($"created auction house : {house.Name}");
                return RedirectToAction("AuctionHousesManage", "Admin");
            }

            return View(house);
        }

        public ViewResult Update(string id)
        {
            return View(Mapper.Map<AuctionHouse, AuctionHouseUpdateViewModel>(_houses.Value.Get(id)));
        }

        [HttpPost]
        public ActionResult Update(AuctionHouseUpdateViewModel house, string oldHouseName)
        {
            if (ModelState.IsValid)
            {
                AuctionHouse newHouse = Mapper.Map<AuctionHouseUpdateViewModel, AuctionHouse>(house);
                _houses.Value.Update(oldHouseName, newHouse);

                _logger.Value.Info($"updated auction house : {house.Name}");
                TempData["message"] = "Auction house updated";

                return RedirectToRoute(new
                {
                    controller = "Admin",
                    action = "AuctionHousesManage",
                    auction = newHouse.Name
                });
            }

            return View(house);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(string name)
        {
            if (_houses.Value.GetAll().Count() == 1)
            {
                TempData["error-message"] = "before you remove the need to create new house";
                return RedirectToAction("AuctionHousesManage", "Admin");
            }

            AuctionHouse house = _houses.Value.Get(name);

            if (house != null)
            {
                _houses.Value.Delete(house.Name);
                _connectionStore = new ConnectionStore(house.Type, _logger);
                _connectionStore.RemoveConnection(house.Location);
            }
            else
            {
                TempData["message"] = $"Not found Auction house : {name}";
            }

            _logger.Value.Info($"deleted auction house : {name}");
            return RedirectToAction("AuctionHousesManage", "Admin");
        }

        public PartialViewResult GetHouses()
        {
            return PartialView("_ListItems", _houses.Value.GetAll().Select(h => h.Name));
        }

        [HttpPost]
        public ActionResult ChangeHouse(string name)
        {
            string url = Url.RouteUrl(new
            {
                controller = "Product",
                action = "ProductsList",
                category = (string)null,
                page = 1,
                auction = name
            });

            if (Request.IsAjaxRequest())
            {
                return Json(new { newurl = url });
            }

            return Redirect(url);
        }
    }
}

Task_1/AuctionStore/AuctionStore.UI/Controllers/CultureController.cs
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace AuctionStore.UI.Controllers
{
    public class CultureController : Controller
    {
        public static List<string> Cultures => new List<string>()
        {
            "ru", "en", "be"
        };

        public ActionResult ChangeCulture(string lang, string returnUrl)
        {
            if (!Cultures.Contains(lang))
            {
                lang = "ru";
            }

            HttpCookie cookie = Request.Cookies["lang"];
            if (cookie != null)
            {
                cookie.Value = lang;
            }
            else
            {
                cookie = new HttpCookie("lang")
                {
                    HttpOnly = false,
                    Value = lang,
                    Expires = DateTime.Now.AddYears(1)
                };
            }

            Response.Cookies.Add(cookie);

            return RedirectToAction("ProductsList", "Product");
        }

        public PartialViewResult Languages()
        {
            return PartialView("_ListItems", Cultures);
        }
    }
}

Task_1/AuctionStore/AuctionStore.UI/Views/Shared/ErrorView.cshtml
@model HandleErrorInfo
@{
    ViewBag.Title = "ErrorView";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Error</h2>

<h3>@Model.Exception.Message</h3>

Task_1/AuctionStore/AuctionStore.UI/Views/Shared/ProductSummary.cshtml
@using Rsc
@model AuctionStore.UI.Models.ProductsViewModels.ProductViewModel

<div class="product-item">
    <div class="item-image">
        <div class="price">
            @if (Model.StartPrice == Model.BidPrice)
            {
                <div class="last-price">@Model.StartPrice.ToString("F") @Html.Partial("_Сurrency")</div>
            }
            else
            {
                <div class="start-price">@Model.StartPrice.ToString("F") @Html.Partial("_Сurrency")</div>
                <div class="last-price">@Model.BidPrice.ToString("F") @Html.Partial("_Сurrency")</div>
            }
        </div>
        <img src="@Url.Action("GetImage", "Product", new {id=Model.Id})"/>
    </div>
    <div class="item-description">
        <div class="title">@Model.Name</div>
        <hr/>
        <h4>@Resource.BidsQuantity: @Model.BidsQuantity</h4>
        <hr/>
        <h4>
           @Resource.TimeLeft: @Model.TimeLeft.ToString(@"dd\.hh\:mm\:ss")
        </h4>
        <hr />
        @Html.ActionLink("..."+Resource.ReadMore, "Details", "Product", new { id = Model.Id, returnUrl = Request.Url.PathAndQuery }, new {@class="button" })
    </div>
</div>

Task_1/AuctionStore/AuctionStore.UI/Views/Shared/_Layout.cshtml
@using System.Security.Claims
@using Rsc
@{
    var claimsIdentity = User.Identity as ClaimsIdentity;
    string house = null;
    if (Request.RequestContext.RouteData.Values["auction"] != null)
    {
        house = Request.RequestContext.RouteData.Values["auction"].ToString();
    }

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>@Resource.Title</title>
    <meta name="description" content="">
    <link href="~/content/grid.css" rel="stylesheet"/>
    <link href="~/content/main.min.css" rel="stylesheet"/>
    <link href="~/content/font-awesome.min.css" rel="stylesheet"/>
</head>
<body>

<header class="main-head">
    <section class="top-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <ul class="top-menu-ul">
                        <li class="dropdown">
                            <a><i class="fa fa-angle-double-down"></i> @Resource.Language </a>
                            <ul class="dropdown-content" id="language">
                                @Html.Action("Languages", "Culture")
                            </ul>
                        </li>
                    </ul>
                    <ul class="top-menu-ul">
                        <li class="dropdown">
                            <a><i class="fa fa-angle-double-down"></i> @Resource.AuctionHouse </a>
                            <ul class="dropdown-content" id="auction-house">
                                @Html.Action("GetHouses", "AuctionHouse")
                            </ul>
                        </li>
                    </ul>
                    <span>
                </span>
            </div>
            <div class="col-md-8">
                <ul class="top-menu-ul right-content">

                    @if (User != null && User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin") || User.IsInRole("Moderator"))
                        {
                            <li class="dropdown">
                                <a><i class="fa fa-angle-double-down"></i> @Resource.AdminPanel </a>
                                <ul class="dropdown-content">
                                    <li>@Html.ActionLink(Resource.ProductManagement, "ProductsManage", "Admin")</li>
                                    <li>@Html.ActionLink(Resource.CategoryManagement, "CategoriesManage", "Admin")</li>
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <li> @Html.ActionLink(Resource.UserManagement, "UsersManage", "Admin")</li>
                                        <li>@Html.ActionLink(Resource.AuctionHouseManagement, "AuctionHousesManage", "Admin")</li>
                                    }
                                </ul>
                            </li>
                        }
                        <li> @Html.ActionLink(Resource.Products, "GetUserProducts", new { controller = "Product" })</li>
                            <li>@Html.ActionLink(Resource.Bids, "UserBids", new { controller = "Bid", returnUrl = Request.Url.PathAndQuery })</li>
                            <li><a href="@Url.Action("UserProfile", "Account")"><i class="fa fa-user"></i> @Resource.UserProfile</a> </li>
                            <li> <a href="@Url.Action("Logout", "Account")"><i class="fa fa-sign-out"></i> @Resource.SignOut</a></li>
                    }
                    else
                    {
                        <li> @Html.ActionLink(Resource.Register, "Register", "Account")</li>
                            <li> <i class="fa fa-sign-in"></i> @Html.ActionLink(Resource.SignIn, "Login", new { controller = "Account" }, new { @class = "sign-in" })</li>
                    }
                </ul>
            </div>
        </div>
    </div>
</section>



    <section class="top-banner">
        <div class="container">
            <a href=@Url.Action("ProductsList","Product")><img src="~/content/img/iynbvttsbqq.jpg" class="logo-img" /></a>
            @Html.ActionLink(Resource.Title + ": "+ house , "ProductsList", new {controller = "Product"}, new {@class = "logo"})
        </div>
    </section>

    <nav class="nav-menu">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="top-menu-ul">
                        <li>@Html.RouteLink(Resource.Main, new
                       {
                           controller = "Product",
                           action = "ProductsList",
                           category = (string)null,
                           page = 1,
                           auction = Request.RequestContext.RouteData.Values["auction"]
                       })</li>
                        <li><a href="">@Resource.AboutUs</a></li>
                        <li><a href="">@Resource.Contacts</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>

</header>

<div class="container">

    @if (TempData["message"] != null)
    {
        <div class="message"><i class="fa fa-check"></i>@TempData["message"]</div>
    }

    @if (TempData["error-message"] != null)
    {
        <div class="error-message"><i class="fa fa-warning"></i>@TempData["error-message"]</div>
    }
</div>


<section class="main-content">
        <div class="container">
                @RenderBody()
            </div>
        </section>

<footer>

    <section class="top-footer">
        <div class="container">
            <div class="footer-contacts">
                <h2>@Resource.Contacts:</h2>
                <ul>
                    <li> <i class="fa fa-map-marker"></i> Storgata 166, Hus 6 0182 Oslo Norway</li>
                    <li><i class="fa fa-mobile-phone"></i> +47 (22) 123 456</li>
                    <li><i class="fa fa-at"></i>email@company.com</li>
                </ul>
            </div>
        </div>
    </section>

    <section class="bottom-footer">
        <div class="container">
            <span>© 2016  Produced by GJekaS</span>
        </div>
    </section>

</footer>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<script>
    $(document).ready(function () {

        $('ul#language>li>a').click(function (e) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ChangeCulture", "Culture")',
                data: {
                    'lang': this.innerText
                },
                success: function () {
                    window.location.reload();
                }
            });
        });

        $('ul#auction-house>li>a').click(function (e) {
            $.ajax({
                type: 'POST',
                url: '@Url.Action("ChangeHouse", "AuctionHouse")',
                data: {
                    'name': this.innerText
                },
                success: function (returndata) {
                    window.location = returndata.newurl;
                }
            });
        });

    });
</script>

<script src="~/Scripts/bootstrap.min.js"></script>
<script src="~/scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

</body>
</html>

Task_1/AuctionStore/AuctionStore.UI/Views/Shared/_ListItems.cshtml
@model IEnumerable<String>

@foreach (var item in Model)
{
    <li><a>@item</a></li>
}

Task_1/AuctionStore/AuctionStore.UI/Views/Shared/_Сurrency.cshtml
$