Task_1/AuctionStore/AuctionStore.UI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AuctionStore.Business.Abstract;
using AuctionStore.UI.Models.EnumsViewModels;

namespace AuctionStore.UI.Controllers
{
    public class NavController : Controller
    {
        private readonly Lazy<ICategoryService> _categoryService;

        public NavController(Lazy<ICategoryService> categoryService)
        {
            _categoryService = categoryService;
        }

        public PartialViewResult CategoriesMenu(string category = null)
        {
            ViewBag.SelectedCategory = category;
            IEnumerable<string> categories =
                this._categoryService.Value.All().Select(c => c.Name).OrderBy(c => c).Distinct();
            return PartialView(categories);
        }

        public PartialViewResult ProductsMenu(ProductStateView? state)
        {
            ViewBag.SelectedProductState = state;
            ProductStateView[] productStates = (ProductStateView[])Enum.GetValues(typeof(ProductStateView));
            return PartialView("_ProductsMenu", productStates);
        }
    }
}

Task_1/AuctionStore/AuctionStore.UI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Web.UI;
using AuctionStore.Business.Abstract;
using AuctionStore.Business.Entities;
using AuctionStore.DAL.EnumsDto;
using AuctionStore.UI.Helpers;
using AuctionStore.UI.Models;
using AuctionStore.UI.Models.ProductsViewModels;
using AutoMapper;
using Microsoft.AspNet.Identity;
using NLog;
using Rsc;

namespace AuctionStore.UI.Controllers
{
    [HandleError(View = "ErrorView")]
    public class ProductController : Controller
    {
        public const int PageSize = 8;

        private readonly Lazy<IProductService> _productService;

        private readonly Lazy<ICategoryService> _categoryService;

        private readonly Lazy<ILogger> _logger;

        public ProductController(Lazy<IProductService> productService, Lazy<ICategoryService> categoryService, Lazy<ILogger> logger)
        {
            _productService = productService;
            _categoryService = categoryService;
            _logger = logger;
        }

        [Authorize(Roles = "User, Admin")]
        public ViewResult Create()
        {
            ViewBag.CategoriesSelectListItem =
                CategoriesHelper.GetCategoriesSelectListItems(_categoryService.Value.All());

            return View(new ProductCreateViewModel()
            {
                Duration = TimeSpan.Parse(ConfigurationManager.AppSettings["MinDuration"])
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User, Admin")]
        public async Task<ActionResult> Create(ProductCreateViewModel product)
        {
            if (product.CategoryId == Guid.Empty.ToString())
            {
                ModelState.AddModelError(string.Empty, Resource.DontSelectCategory);
            }

            if (ModelState.IsValid)
            {
                if (Request.Files.Count != 0)
                {
                    var file = Request.Files[0];
                    if (file?.ContentLength != 0)
                    {
                        byte[] fileBytes = new byte[file.ContentLength];
                        file.InputStream.Read(fileBytes, 0, fileBytes.Length);
                        product.ImageData = Convert.ToBase64String(fileBytes);
                        product.ImageType = file.ContentType;
                    }
                }

                Product entry = Mapper.Map<ProductCreateViewModel, Product>(product);
                await _productService.Value.Create(entry, Guid.Parse(User.Identity.GetUserId()));

                _logger.Value.Info($"product {product.Name} created by {User.Identity.Name}");
                TempData["message"] = Resource.ProductCreated + $": {product.Name}";
                return RedirectToAction("GetUserProducts");
            }

            ViewBag.CategoriesSelectListItem =
                CategoriesHelper.GetCategoriesSelectListItems(_categoryService.Value.All());
            return View(product);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Guid id, string returnUrl)
        {
            Product product = await _productService.Value.Get(id);
            if (product != null)
            {
                await _productService.Value.Delete(id);
                TempData["message"] = Resource.ProductDeleted;
                _logger.Value.Info($"product {product.Name} deleted by {User.Identity.Name}");
            }

            TempData["error-message"] = "Product not found";
            return Redirect(returnUrl);
        }

        [Authorize(Roles = "User, Admin")]
        public async Task<ActionResult> Update(Guid id)
        {
            if (id == Guid.Empty)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Product product = await _productService.Value.Get(id);
            ProductUpdateViewModel model = Mapper.Map<Product, ProductUpdateViewModel>(product);

            ViewBag.CategoriesSelectListItem =
                CategoriesHelper.GetCategoriesSelectListItems(_categoryService.Value.All());
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "User, Admin")]
        public async Task<ActionResult> Update(ProductUpdateViewModel product)
        {
            if (product.CategoryId == Guid.Empty)
            {
                ModelState.AddModelError(string.Empty, Resource.DontSelectCategory);
            }

            if (ModelState.IsValid)
            {
                if (Request.Files.Count != 0)
                {
                    var file = Request.Files[0];
                    if (file?.ContentLength != 0)
                    {
                        byte[] fileBytes = new byte[file.ContentLength];
                        file.InputStream.Read(fileBytes, 0, fileBytes.Length);
                        product.ImageData = Convert.ToBase64String(fileBytes);
                        product.ImageType = file.ContentType;
                    }
                }

                Product entry = Mapper.Map<ProductUpdateViewModel, Product>(product);
                await _productService.Value.Update(entry);

                TempData["message"] = Resource.ProductUpdated + $": {product.Name}";
                _logger.Value.Info($"product {product.Name} created by {User.Identity.Name}");
                return RedirectToAction("GetUserProducts");
            }

            ViewBag.CategoriesSelectListItem =
                CategoriesHelper.GetCategoriesSelectListItems(_categoryService.Value.All());
            return View(product);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<ActionResult> ChangeState(Guid id, ProductState newState, string returnUrl)
        {
            await _productService.Value.ChangeState(id, newState);
            return Redirect(returnUrl);
        }

        public async Task<ViewResult> ProductsList(string category = null, int page = 1)
        {
            IEnumerable<Product> products;
            int totalItems = 0;
            products = await _productService.Value.All();
            products = products.Where(p => p.IsActual()).ToList();

            if (category == null)
            {
                totalItems = products.Count();
            }
            else
            {
                Category categoryEntry = await _categoryService.Value.Get(category);
                Guid categoryId = categoryEntry.Id;

                products = products.Where(p => p.CategoryId == categoryId).ToList();
                totalItems = products.Count();
            }

            IEnumerable<ProductViewModel> productsView =
                Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(
                    products
                    .OrderBy(p => p.StartDate)
                        .Skip((page - 1) * PageSize)
                        .Take(PageSize)
                        .ToList());

            ProductsListViewModel model = new ProductsListViewModel()
            {
                Products = productsView,
                PagingInfo = new PagingInfo()
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = totalItems
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public async Task<ActionResult> Details(string id, string returnUrl)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            ViewBag.ReturnUrl = returnUrl;

            Product product = await _productService.Value.Get(Guid.Parse(id));
            if (!product.IsActual())
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(Mapper.Map<Product, ProductViewModel>(product));
        }

        [Authorize]
        public async Task<ActionResult> GetUserProducts()
        {
            IEnumerable<Product> products =
                await _productService.Value.UserProducts(Guid.Parse(User.Identity.GetUserId()));

            return
                View(Mapper.Map<IEnumerable<Product>, IEnumerable<ProductViewModel>>(products.OrderBy(p => p.StartDate)));
        }

        [OutputCache(Duration = 50000, VaryByParam = "id", Location = OutputCacheLocation.ServerAndClient)]
        public async Task<ActionResult> GetImage(Guid id)
        {
            Product product = await _productService.Value.Get(id);

            if (product.ImageData == null)
            {
                var path = Server.MapPath("~/Content/img");
                var file = Directory.GetFiles(path, $"NoPhoto.*").FirstOrDefault();
                if (file == null)
                {
                    return null;
                }

                return File(Path.Combine(path, file), $"image/{Path.GetExtension(file)}");
            }

            byte[] imageBytes = Convert.FromBase64String(product.ImageData);
            return File(imageBytes, product.ImageType);
        }
    }
}

Task_1/AuctionStore/AuctionStore.UI/Controllers/UserController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using AuctionStore.Business.Entities;
using AuctionStore.Business.Helpers;
using AuctionStore.Business.Models;
using AuctionStore.DAL.EnumsDto;
using AuctionStore.UI.Helpers;
using AuctionStore.UI.Models.UserViewModels;
using AuctionStore.UI.UserService;
using AutoMapper;

namespace AuctionStore.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    [HandleError(View = "ErrorView")]
    public class UserController : Controller
    {
        private readonly WcfUserServiceClient _userClient;

        public UserController(WcfUserServiceClient userClient)
        {
            _userClient = userClient;
        }

        public ViewResult Create()
        {
            return View(new CreateUserViewModel()
            {
                TimeZonesSelectListItems = TimeZoneHelper.GetTimeZonesSelectListItems()
            });
        }

        [HttpPost]
        public async Task<ActionResult> Create(CreateUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = Mapper.Map<CreateUserViewModel, User>(model);
                OperationResult result = await _userClient.RegisterAsync(user);
                if (result.Success)
                {
                    TempData["message"] = $"Пользователь создан :{user.UserName}";
                    return RedirectToAction("UsersManage", "Admin");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error);
                }
            }

            model.TimeZonesSelectListItems = TimeZoneHelper.GetTimeZonesSelectListItems();
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> AddToRole(string userId, Role role)
        {
            OperationResult result = await _userClient.AddToRoleAsync(userId, role);
            if (!result.Success)
            {
                TempData["error-message"] = result.Errors.ConcatAll();
            }

            return RedirectToAction("UsersManage", "Admin");
        }

        [HttpPost]
        public async Task<ActionResult> DeleteFromRole(string userId, Role role)
        {
            OperationResult result = await _userClient.RemoveFromRoleAsync(userId, role);
            if (!result.Success)
            {
                TempData["error-message"] = result.Errors.ConcatAll();
            }

            return RedirectToAction("UsersManage", "Admin");
        }

        [HttpPost]
        public async Task<ActionResult> DeleteUser(string id)
        {
            OperationResult result = await _userClient.DeleteUserAsync(id);
            if (result.Success)
            {
                TempData["message"] = "User deleted";
            }
            else
            {
                TempData["error-message"] = result.Errors.ConcatAll();
            }
           
            return RedirectToAction("UsersManage", "Admin");
        }
    }
}

Task_1/AuctionStore/AuctionStore.UI/Views/Admin/AddModeratorCategory.cshtml
@{
    ViewBag.Title = "AddModeratorCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<h2>AddModeratorCategory</h2>

@if (!((IEnumerable<SelectListItem>)ViewBag.Categories).Any())
{
    <div>Категории для добавления не найдены</div>
}
else
{
    using (Html.BeginForm())
    {
        @Html.Hidden("userId", (string)ViewBag.UserId)
        @Html.DropDownList("category", (IEnumerable<SelectListItem>)ViewBag.Categories)
        <div>@Request.RequestContext.RouteData.Values["auction"]</div>
        <input type="submit" value="Ok" />
    }

}

Task_1/AuctionStore/AuctionStore.UI/Views/Admin/AuctionHousesManage.cshtml
@using Rsc
@model IEnumerable<AuctionStore.Business.Entities.AuctionHouse>
@{
    ViewBag.Title = "AuctionHousesManage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@if (Model!=null && Model.Count()!=0)
{
    <div class="row">
        <div class="col-md-12">
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Location</th>
                        <th style="text-align: center">@Resource.Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var house in Model)
                    {
                        <tr>
                            <td>@Html.ActionLink(house.Name, "Update", new {id = house.Name , controller="AuctionHouse"})</td>
                            <td>@house.Location</td>
                            <td class="action">
                                @using (Html.BeginForm("Delete", "AuctionHouse"))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.Hidden("name", house.Name)
                                    <input type="submit" value=@Resource.Delete class="button blue"/>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
}

<div>
    @Html.ActionLink(Resource.Create, "Create", new { controller = "AuctionHouse" }, new { @class = "button" })
</div>

Task_1/AuctionStore/AuctionStore.UI/Views/Admin/CategoriesManage.cshtml
@using Rsc
@model IEnumerable<AuctionStore.UI.Models.CategoriesViewModels.CategoryViewModel>
@{
    ViewBag.Title = Resource.CategoryManagement;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@ViewBag.Title</h2>

@if (Model.Count() != 0)
{
    <div class="row">
        <div class="col-md-12">
            <table>
                <thead>
                <tr>
                    <th>@Html.DisplayNameFor(m => m.Name)</th>
                    <th>@Html.DisplayNameFor(m => m.Description)</th>
                    <th style="text-align: center">@Resource.Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.ActionLink(item.Name, "Update", new {controller = "Category", id = item.Id}, new {@class = "item-title"})</td>
                        <td>@Html.DisplayFor(m => item.Description)</td>
                        <td class="action">
                            @using (Html.BeginForm("Delete", "Category"))
                            {
                                @Html.AntiForgeryToken()
                                @Html.Hidden("id", item.Id)
                                <input type="submit" value=@Resource.Delete class="button blue"/>
                            }
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
}
else
{
    <span>@Resource.NoCategory</span>
}

<div>
    @Html.ActionLink(Resource.Create, "Create", new {controller = "Category"}, new {@class = "button"})
</div>

Task_1/AuctionStore/AuctionStore.UI/Views/Admin/ModeratorClaims.cshtml
@using AuctionStore.Business.Entities
@using AuctionStore.Business.Enums
@model AuctionStore.UI.Models.ModeratorCategoriesManageViewModel
@{
    ViewBag.Title = "ModeratorRights";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col-md-12">
        <ul>
            <h2>Категории модератора для управления</h2>
            @foreach (var claim in Model.Claims)
            {
                <li>
                    @{
                        var category = $"Аукционный дом: {claim.Value.Split('/')[0]}| Категория: {claim.Value.Split('/')[1]}";
                    }

                    @using (Html.BeginForm("DeleteCategoryFromManageModerator", "Admin"))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("userId", Model.Id)
                        @Html.Hidden("categoryName", claim.Value)
                        <input type="submit" value="- @category"/>
                    }
                </li>
            }
        </ul>

@if (Model.Categories.Count()!=0)
{
    using (Html.BeginForm("AddCategoryToManageModerator", "Admin", FormMethod.Post, new {@class = "form"}))
    {
        <h2>Добавить категорию для управления</h2>
        @Html.AntiForgeryToken()
        @Html.Hidden("userId", Model.Id)
        @Html.DropDownList("categoryName", Model.Categories)
        <input type="submit" value="add"/>
    }
}
</div>
</div>

Task_1/AuctionStore/AuctionStore.UI/Views/Admin/ProductsManage.cshtml
@using AuctionStore.Business.Enums
@using AuctionStore.DAL.EnumsDto
@using AuctionStore.UI.Models.EnumsViewModels
@using Rsc
@model IEnumerable<AuctionStore.UI.Models.ProductsViewModels.ProductViewModel>
@{
    ViewBag.Title = Resource.ProductManagement;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Resource.ProductManagement</h2>

<nav class="category">
    <div class="row">
        <div class="col-md-12">
            @Html.Action("ProductsMenu", "Nav")
        </div>
    </div>
</nav>

<div class="row">
    <div class="col-md-12">
        <table>
            <thead>
            <tr>
                <th>@Html.DisplayNameFor(m => m.Name)</th>
                <th>@Html.DisplayNameFor(m => m.Duration)</th>
                <th>@Html.DisplayNameFor(m => m.StartDate)</th>
                <th>@Html.DisplayNameFor(m => m.StartPrice)</th>
                <th>@Html.DisplayNameFor(m => m.Category.Name)</th>
                <th>@Html.DisplayNameFor(m => m.ImageData)</th>
                <th>@Html.DisplayNameFor(m => m.State)</th>
                <th>@Html.DisplayNameFor(m => m.TimeLeft)</th>
                <th colspan="2">@Resource.Actions</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(m => item.Name)</td>
                    <td>@Html.DisplayFor(m => item.Duration)</td>
                    <td>@Html.DisplayDateTime(item.StartDate, (string) ViewBag.TimeZoneId)</td>
                    <td>@Html.DisplayFor(m => item.StartPrice)</td>
                    <td>@Html.DisplayFor(m => item.Category.Name)</td>
                    <td><img width="100" height="100" src="@Url.Action("GetImage", "Product", new {id = item.Id})"/></td>
                    <td>@Html.DisplayForEnum(item.State)</td>
                    <td>@item.TimeLeft.ToString(@"dd\.hh\:mm\:ss")</td>

                    <td>
                        @using (Html.BeginForm("ChangeState", "Product", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("id", item.Id)
                            @Html.Hidden("returnUrl", Request.Url)

                            switch (item.State)
                            {
                                case ProductStateView.Selling:
                                {
                                    @Html.Hidden("newState", ProductState.Banned)
                                    <input type="submit" value=@Resource.Ban class="button blue"/>
                                }
                                    break;
                                case ProductStateView.Draft:
                                case ProductStateView.Banned:
                                {
                                    @Html.Hidden("newState", ProductState.Selling)
                                    <input type="submit" value=@Resource.Publish class="button blue"/>
                                }
                                    break;
                                case ProductStateView.Sold:
                                {
                                    <span> - </span>
                                }
                                    break;
                            }
                        }
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "Product", FormMethod.Post))
                        {
                            @Html.AntiForgeryToken()
                            @Html.Hidden("id", item.Id)
                            @Html.Hidden("returnUrl", Request.Url)
                            <input type="submit" value=@Resource.Delete class="button blue"/>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

Task_1/AuctionStore/AuctionStore.UI/Views/Admin/RoleRightss.cshtml
@model IEnumerable<IGrouping<Guid, AuctionStore.Business.Entities.UserClaim>>
@{
    ViewBag.Title = "ModeratorsManage";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ModeratorsManage</h2>
@if (Model.Count() != 0)
{

    <table>
        <thead>
        <tr>

        </tr>
        </thead>
        <tbody>

        <tr>
            @foreach (var user in Model)
            {
                <td> @user.Key</td>
                foreach (var claims in user)
                {
                    <td>@claims.Type</td>
                    <td>@claims.Value</td>
                }
                <td>
                    @Html.ActionLink("Добавить категорию для управления", "AddModeratorCategory", new {userId = user.Key})
                    @Html.ActionLink("Удалить категорию для управления", "DeleteModeratorCategory", new {userId = user.Key})
                </td>
            }
        </tr>
        </tbody>
    </table>
}

Task_1/AuctionStore/AuctionStore.UI/Views/Admin/UsersManage.cshtml
@using AuctionStore.UI.Models.EnumsViewModels
@using Rsc
@model IEnumerable<AuctionStore.UI.Models.UserViewModels.UserViewModel>
@{
    ViewBag.Title = Resource.UserManagement;
    Layout = "~/Views/Shared/_Layout.cshtml";
    Array roles = Enum.GetValues(typeof (RoleView));
}

<div>@ViewBag.Title</div>
@if (Model.Count() != 0)
{
    <table>
        <thead>
        <tr>
            <th>@Html.DisplayNameFor(m => m.UserName)</th>
            <th>@Html.DisplayNameFor(m => m.FirstName)</th>
            <th>@Html.DisplayNameFor(m => m.LastName)</th>
            <th>@Html.DisplayNameFor(m => m.RegistrationDate)</th>
            <th>@Html.DisplayNameFor(m => m.UserRoles)</th>
            <th>@Resource.DeleteRole</th>
            <th>@Resource.AddRole</th>
            <th>@Resource.Actions</th>
        </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(m => item.UserName)</td>
                <td>@Html.DisplayFor(m => item.FirstName)</td>
                <td>@Html.DisplayFor(m => item.LastName)</td>
                <td>@Html.DisplayDateTime(item.RegistrationDate, (string)ViewBag.TimeZoneId)</td>
                <td>
                    @foreach (var role in item.UserRoles)
                    {
                        <span>@Html.DisplayForEnum(role)</span>
                    }
            </td>

                <td>
                    @foreach (var role in roles)
                    {
                        if ((RoleView) role == RoleView.Admin)
                        {
                            continue;
                        }

                        if (item.UserRoles.Contains((RoleView)role))
                        {
                            using (Html.BeginForm("DeleteFromRole", "User"))
                            {
                                @Html.Hidden("userId", item.Id)
                                @Html.Hidden("role", (RoleView) role)
                                <input type="submit" value="- @Html.DisplayForEnum((RoleView) role)" class="button blue"/>
                            }
                        }
                    }
                </td>
                <td>
                    @foreach (var role in roles)
                    {
                        if ((RoleView) role == RoleView.Admin)
                        {
                            continue;
                        }

                        if (!item.UserRoles.Contains((RoleView)role))
                        {
                            using (Html.BeginForm("AddToRole", "User"))
                            {
                                @Html.Hidden("userId", item.Id)
                                @Html.Hidden("role", (RoleView) role)
                                <input type="submit" value="+ @Html.DisplayForEnum((RoleView)role)" class="button blue"/>
                            }
                        }
                    }
                </td>
                <td>
                    @using (Html.BeginForm("DeleteUser", "User", FormMethod.Post))
                    {
                        @Html.Hidden("id", item.Id)
                        <input type="submit" class="button blue" value=@Resource.Delete/>
                    }
                </td>
               @if (item.UserRoles.Contains(RoleView.Moderator))
               {
                   <td>@Html.ActionLink("Уравление модератором", "ModeratorClaims", new {id = item.Id})</td>
               }
            </tr>
        }
            
        </tbody>
    </table>
}
else
{
    <span>@Resource.NoUsers</span>
}

<div style="text-align: center">@Html.ActionLink(Resource.Create, "Create", new { controller = "User" }, new { @class = "button" })</div>